### ISSUE TITLE
Chocolaty package not up to date

### ISSUE THREAD

**Issue by stefanroelofs** [Flow-Launcher/chocolatey-package#3]
Chocolaty package is no longer up to date. See here that latest version is 1.16.2:
https://community.chocolatey.org/packages/flow-launcher

However actually latest version is v1.17.2

I'm not sure where the problem is. The flow-launcher.nuspec file does reference to the lastest version.
Thanks!

**Comment by jjw24** [comment]
It's the submission call that's erroring silently. I haven't had the time to look into and fix yet.

**Comment by jjw24** [comment]
Submission error has been fixed. All missing versions from v1.16.2 onwards have been submitted to Chocolatey for approval, they should show up along with v1.18.0 soon.
